# 예외 처리하기와 미루기

# try-catch 문

1. try 블록에는 예외가 발생할 가능성이 있는 코드를 작성하고 try 블록 안에서 예외가 발생하는 경우 catch 블록이 수행됨

2. 프로그래머가 예외를 처리해줘야 하는 예 (배열의 오류 처리)

```

public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr = {1, 2, 3, 4, 5};
		
		try {
			for (int i=0; i<=5; i++) {
				System.out.println(arr[i]);
			}
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println(e.getMessage());
			System.out.println(e.toString());
		}
		
	}

Index 5 out of bounds for length 5
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5

```

# try-catch-finally 문

1. finally 블럭에서 파일을 닫거나 네트웍을 닫는 등의 리소스 해제 구현을 함

2. try() 블럭이 수행되는 경우, finally() 블럭은 항상 수행 됨

3. 여러개의 예외 블록이 있는 경우 각각에서 리소스를 해제하지 않고 finally 블록에서 해제하도록 구현함

4. 컴파일러에 의해 예외가 처리 되는 예 

```

Try 구문이 불리면 finally는 무조건 불린다.

package ch08;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class FileExceptionHandling {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		FileInputStream fis = null;
		
		try {
			fis = new FileInputStream("a.txt");
			
			System.out.println("read");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			System.out.println(e.getMessage());
			
		} finally {
			
			if (fis != null) {
				try {
					fis.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
			System.out.println("finally");
		}
	}

}


```

# try-with-resources 문

1. 리소스를 사용하는 경우 close() 하지 않아도 자동으로 해제 되도록 함

```

package ch08;

public class AutoCloseableObj implements AutoCloseable {

	@Override
	public void close() throws Exception {
		// TODO Auto-generated method stub
		System.out.println("closing");
	}
	
}



package ch08;

public class AutoCloseTest {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		AutoCloseableObj obj = new AutoCloseableObj();
		
		try (obj) {
			
		} catch (Exception e) {
			System.out.println("exception" + e.getMessage());
		}
		
		System.out.println("end");
	}

}


```

# 예외 처리 미루기

1. throws를 이용하면 예외가 발생할 수 있는 부분을 사용하는 문장에서 예외를 처리할 수 있음

